title: Air Fry Till I Die
description: Giving the UH community a way to spice up their cooking
google_analytics:
show_downloads: false
theme: jekyll-theme-midnight
github:
  is_project_page: true
  repository_url: https://github.com/Air-Fry-Till-I-Die/Air-Fry-Till-I-Die
